events { worker_connections 1024; }

http {
    include mime.types;
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            proxy_set_header Host $host;
            try_files $uri $uri/ /index.html;
        }

        location /users/query {
            set $users_svc users-service;
            proxy_set_header Host $host;
            proxy_pass http://$users_svc:3000/query;
        }

        location /data/query {
            set $data_svc data-service;
            proxy_set_header Host $host;
            proxy_pass http://$data_svc:3000/query;
        }

        location /healthz {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
        
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    }
}