// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type LoginInput struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Totp     *string `json:"totp,omitempty"`
}

type LoginResponse struct {
	Username string `json:"username"`
	Token    string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Password string    `json:"password"`
	Totp     *string   `json:"totp,omitempty"`
}

type UserCredentialsInputInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
