package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"data-service/graph/model"
	"data-service/internal/auth"
	"fmt"
)

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.NewCard) (*model.Card, error) {
	username, err := auth.ValidateToken(ctx)
	if err != nil {
		return nil, err
	}

	var card model.Card
	if err := r.DB.QueryRow(ctx, `
		WITH inserted AS (
			INSERT INTO cards (owner, name, description, color_id, icon_id)
        	SELECT $1, $2, $3, 
            	(SELECT id FROM colors WHERE name = $4),
            	(SELECT id FROM icons WHERE name = $5)
			RETURNING id, name, description, completedDays, color_id, icon_id
		)
		SELECT i.id, i.name, i.description, i.completedDays, c.name, ic.name
		FROM inserted i
		LEFT JOIN colors c ON i.color_id = c.id
		LEFT JOIN icons ic ON i.icon_id = ic.id
	`, username, input.Name, input.Desc, input.Color, input.Icon).Scan(
		&card.ID,
		&card.Name,
		&card.Desc,
		&card.CompletedDays,
		&card.Color,
		&card.Icon,
	); err != nil {
		return nil, err
	}

	return &card, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, input string) (bool, error) {
	username, err := auth.ValidateToken(ctx)
	if err != nil {
		return false, err
	}

	if _, err := r.DB.Exec(ctx, `
		DELETE FROM cards
		WHERE owner = $1 AND id=$2
	`, username, input); err != nil {
		return false, err
	}

	return true, nil
}

// CompleteDay is the resolver for the completeDay field.
func (r *mutationResolver) CompleteDay(ctx context.Context, input string) (bool, error) {
	fmt.Println("complete", input)

	return true, nil
}

// GetCards is the resolver for the getCards field.
func (r *queryResolver) GetCards(ctx context.Context) ([]*model.Card, error) {
	username, err := auth.ValidateToken(ctx)
	if err != nil {
		return nil, err
	}

	var cards []*model.Card
	rows, err := r.DB.Query(ctx, `
		SELECT C.id, C.name, C.description, C.completedDays, COL.name, I.name
		FROM cards C
		LEFT JOIN colors COL ON C.color_id=COL.id
		LEFT JOIN icons I ON C.icon_id=I.id
		WHERE owner = $1
	`, username)
	if err != nil {
		return nil, err
	}

	for rows.Next() {
		var card model.Card
		if err := rows.Scan(
			&card.ID,
			&card.Name,
			&card.Desc,
			&card.CompletedDays,
			&card.Color,
			&card.Icon,
		); err != nil {
			return nil, err
		}
		cards = append(cards, &card)
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}

	return cards, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
