name: Client Pipeline

on:
  push:
    branches:
      - main
    # paths:
    #   - 'client/**'

jobs:
  testing:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install
    - name: Check style
      run: bun run lint


  deploy:
    needs: testing
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish
      run: |-
          docker build --tag "eeritvan/tracker-client:$GITHUB_SHA" .
          docker push "eeritvan/tracker-client:$GITHUB_SHA"
