name: client pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Check style
      run: bun run lint

  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Run tests
      run: bun run coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: client
        name: client-coverage
        path: client/coverage
        fail_ci_if_error: true

  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: false
          tags: |
            eeritvan/tracker-client:${{ github.sha }}
            eeritvan/tracker-client:latest
          cache-from: type=registry,ref=eeritvan/tracker-client:buildcache
          cache-to: type=registry,ref=eeritvan/tracker-client:buildcache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/client-image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-image
          path: ${{ runner.temp }}/client-image.tar
  
  e2e:
    needs: [build]
    uses: ./.github/workflows/e2e.yml

  deploy:
    needs: [e2e]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: client-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/client-image.tar
    - name: Push Docker image
      run: |
        docker push eeritvan/tracker-client:${{ github.sha }}
        docker push eeritvan/tracker-client:latest