name: Check data-service

on:
  push:
    branches:
      - main
    # paths:
    #   - 'data-service/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: data-service
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    
    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: go test ./...

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: data-service
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish
      uses: docker/build-push-action@v6
      with:
        context: ./data-service
        push: true
        tags: |
          eeritvan/tracker-data-svc:${{ github.sha }}
          eeritvan/tracker-data-svc:latest
        cache-from: type=registry,ref=eeritvan/tracker-data-svc:buildcache
        cache-to: type=registry,ref=eeritvan/tracker-data-svc:buildcache,mode=max
