name: e2e tests

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download client image
      uses: actions/download-artifact@v4
      with:
        name: client-image
        path: ${{ runner.temp }}/images

    - name: Download users service image
      uses: actions/download-artifact@v4
      with:
        name: users-svc-image
        path: ${{ runner.temp }}/images

    - name: Download data service image
      uses: actions/download-artifact@v4
      with:
        name: data-svc-image
        path: ${{ runner.temp }}/images

    - name: Load Docker images
      run: |
        docker load --input ${{ runner.temp }}/images/client-image.tar
        docker load --input ${{ runner.temp }}/images/users-svc-image.tar
        docker load --input ${{ runner.temp }}/images/data-svc-image.tar

    - name: Start docker compose
      env:
        POSTGRES_PASSWORD: postgres
        JWT_KEY: secretkey
      run: docker compose up -d

    - name: Wait for client
      run: |
        until curl -sSf http://localhost:5173; do
          netstat -t
          docker ps -a
          sleep 1
        done

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Deps
      run: bun install --frozen-lockfiles
      working-directory: client

    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: bunx playwright test
      working-directory: client
