name: e2e tests
on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download client image
      uses: actions/download-artifact@v4
      with:
        name: client-image
        path: ${{ runner.temp }}
    - name: Load client image
      run: docker load --input ${{ runner.temp }}/client-image.tar

    - name: Download data-service image
      uses: actions/download-artifact@v4
      with:
        name: data-svc-image
        path: ${{ runner.temp }}
    - name: Load data service image
      run: docker load --input ${{ runner.temp }}/data-svc-image.tar

    - name: Download users-service image 
      uses: actions/download-artifact@v4
      with:
        name: users-svc-image
        path: ${{ runner.temp }}
    - name: Load users service image
      run: docker load --input ${{ runner.temp }}/users-svc-image.tar

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup environment
      run: |
        echo "POSTGRES_PASSWORD=password123" >> .env
        echo "JWT_KEY=secret123" >> .env

    - name: Start services
      run: |
        docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
        sleep 10

    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      run: bunx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
