name: e2e tests
on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print workflow info
      run: |
        echo "skipping for now."


## playwright tests here later. I've now idea how to get all the services up and
## running seamlessly.