name: CI/CD pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'data-service/**'
      - 'users-service/**'

jobs:
  client:
    if: contains(github.event.head_commit.modified, 'client/') || contains(github.event.head_commit.added, 'client/')
    uses: ./.github/workflows/client.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  users-service:
    if: contains(github.event.head_commit.modified, 'users-service/') || contains(github.event.head_commit.added, 'users-service/')
    uses: ./.github/workflows/users-service.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  data-service:
    if: contains(github.event.head_commit.modified, 'data-service/') || contains(github.event.head_commit.added, 'data-service/')
    uses: ./.github/workflows/data-service.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    needs: [client, users-service, data-service]
    uses: ./.github/workflows/e2e.yml

  deploy-client:
    needs: [e2e, client]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: client-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/client-image.tar
    - name: Push Docker image
      run: |
        docker push eeritvan/tracker-client:${{ github.sha }}
        docker push eeritvan/tracker-client:latest

  deploy-users-service:
    needs: [e2e, users-service]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: users-svc-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/users-svc-image.tar
    - name: Push Docker image
      run: |
        docker push eeritvan/tracker-users-svc:${{ github.sha }}
        docker push eeritvan/tracker-users-svc:latest

  deploy-data-service:
    needs: [e2e, data-service]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: data-service
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: data-svc-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/data-svc-image.tar
    - name: Push Docker image
      run: |
        docker push eeritvan/tracker-data-svc:${{ github.sha }}
        docker push eeritvan/tracker-data-svc:latest
