name: Check user-service

on:
  push:
    branches:
      - main
    paths:
      - 'users-service/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    
    - name: Install dependencies
      run: go mod download

    - name: Run Unit Tests
      run: go test ./...