name: Check user-service

on:
  push:
    branches:
      - main
    paths:
      - 'users-service/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    - name: Install dependencies
      run: go mod download
    - name: Run Unit Tests
      run: go test -covermode=atomic -coverprofile=coverage.out $(cat testdirs.txt)
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish
      uses: docker/build-push-action@v6
      with:
        context: ./users-service
        push: true
        tags: |
          eeritvan/tracker-users-svc:${{ github.sha }}
          eeritvan/tracker-users-svc:latest
        cache-from: type=registry,ref=eeritvan/tracker-users-svc:buildcache
        cache-to: type=registry,ref=eeritvan/tracker-users-svc:buildcache,mode=max
