name: user-service pipeline

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        cache-dependency-path: users-service/go.sum
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: users-service

  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        cache-dependency-path: users-service/go.sum
    - name: Install dependencies
      run: go mod download
    - name: Run Unit Tests
      run: go test -covermode=atomic -coverprofile=coverage.out $(cat testdirs.txt)
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: users-service
        name: users-service-coverage
        directory: ./users-service
        fail_ci_if_error: true

  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: users-service
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./users-service
          push: false
          tags: |
            eeritvan/tracker-users-svc:${{ github.sha }}
            eeritvan/tracker-users-svc:latest
          cache-from: type=registry,ref=eeritvan/tracker-users-svc:buildcache
          cache-to: type=registry,ref=eeritvan/tracker-users-svc:buildcache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/users-svc-image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: users-svc-image
          path: ${{ runner.temp }}/users-svc-image.tar
