// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const login = `-- name: Login :one
SELECT id, name, password_hash
FROM Users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, login, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const signup = `-- name: Signup :one
INSERT INTO Users (name, password_hash)
VALUES ($1, $2)
RETURNING id, name
`

type SignupParams struct {
	Name         string
	PasswordHash string
}

type SignupRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (SignupRow, error) {
	row := q.db.QueryRow(ctx, signup, arg.Name, arg.PasswordHash)
	var i SignupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
