// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const login = `-- name: Login :one
SELECT id, name, password_hash
FROM Users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, login, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const signup = `-- name: Signup :many
INSERT INTO Users (name, password_hash)
VALUES ($1, $2)
RETURNING id, name
`

type SignupParams struct {
	Name         string
	PasswordHash string
}

type SignupRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) ([]SignupRow, error) {
	rows, err := q.db.Query(ctx, signup, arg.Name, arg.PasswordHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignupRow
	for rows.Next() {
		var i SignupRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
