// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
)

type Tracker struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description *string
}

type User struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
}
