// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTracker = `-- name: AddTracker :one
INSERT INTO trackers (owner_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, description
`

type AddTrackerParams struct {
	OwnerID     uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) AddTracker(ctx context.Context, arg AddTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, addTracker, arg.OwnerID, arg.Title, arg.Description)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const deleteTracker = `-- name: DeleteTracker :exec
DELETE FROM trackers
WHERE id = $1
  AND owner_id = $2
`

type DeleteTrackerParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteTracker(ctx context.Context, arg DeleteTrackerParams) error {
	_, err := q.db.Exec(ctx, deleteTracker, arg.ID, arg.OwnerID)
	return err
}

const editTracker = `-- name: EditTracker :one
UPDATE trackers
SET
    title = COALESCE($3, title),
    description = COALESCE($4, description)
WHERE id = $1
  AND owner_id = $2
RETURNING id, owner_id, title, description
`

type EditTrackerParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       *string
	Description *string
}

func (q *Queries) EditTracker(ctx context.Context, arg EditTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, editTracker,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
	)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getTracker = `-- name: GetTracker :many
SELECT
  t.id,
  t.owner_id,
  t.title,
  t.description,
  COALESCE(
    array_agg(tc.completed_on ORDER BY tc.completed_on)
      FILTER (WHERE tc.completed_on IS NOT NULL),
    ARRAY[]::date[]
  ) AS completed_days
FROM trackers t
LEFT JOIN tracker_completions tc
  ON tc.tracker_id = t.id
WHERE t.owner_id = $1
GROUP BY t.id, t.owner_id, t.title, t.description
`

type GetTrackerRow struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Title         string
	Description   *string
	CompletedDays interface{}
}

func (q *Queries) GetTracker(ctx context.Context, ownerID uuid.UUID) ([]GetTrackerRow, error) {
	rows, err := q.db.Query(ctx, getTracker, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackerRow
	for rows.Next() {
		var i GetTrackerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.CompletedDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracker2 = `-- name: GetTracker2 :many
SELECT
  t.id,
  t.owner_id,
  t.title,
  t.description,
  tc.completed_on
FROM trackers t
LEFT JOIN tracker_completions tc
  ON tc.tracker_id = t.id
WHERE t.owner_id = $1
ORDER BY t.id, tc.completed_on
`

type GetTracker2Row struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description *string
	CompletedOn pgtype.Date
}

func (q *Queries) GetTracker2(ctx context.Context, ownerID uuid.UUID) ([]GetTracker2Row, error) {
	rows, err := q.db.Query(ctx, getTracker2, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTracker2Row
	for rows.Next() {
		var i GetTracker2Row
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.CompletedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
