// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTracker = `-- name: AddTracker :one
INSERT INTO trackers (owner_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, description
`

type AddTrackerParams struct {
	OwnerID     uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) AddTracker(ctx context.Context, arg AddTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, addTracker, arg.OwnerID, arg.Title, arg.Description)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const deleteTracker = `-- name: DeleteTracker :exec
DELETE FROM trackers
WHERE id = $1
  AND owner_id = $2
`

type DeleteTrackerParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteTracker(ctx context.Context, arg DeleteTrackerParams) error {
	_, err := q.db.Exec(ctx, deleteTracker, arg.ID, arg.OwnerID)
	return err
}

const editTracker = `-- name: EditTracker :one
UPDATE trackers
SET
    title = COALESCE($3, title),
    description = COALESCE($4, description)
WHERE id = $1
  AND owner_id = $2
RETURNING id, owner_id, title, description
`

type EditTrackerParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       *string
	Description *string
}

func (q *Queries) EditTracker(ctx context.Context, arg EditTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, editTracker,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
	)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getTracker = `-- name: GetTracker :many
SELECT id, owner_id, title, description
FROM trackers
WHERE owner_id = $1
`

func (q *Queries) GetTracker(ctx context.Context, ownerID uuid.UUID) ([]Tracker, error) {
	rows, err := q.db.Query(ctx, getTracker, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tracker
	for rows.Next() {
		var i Tracker
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
