// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTracker = `-- name: AddTracker :one
INSERT INTO trackers (owner_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, description
`

type AddTrackerParams struct {
	OwnerID     uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) AddTracker(ctx context.Context, arg AddTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, addTracker, arg.OwnerID, arg.Title, arg.Description)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
	)
	return i, err
}
