// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracker_completions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTrackerCompletion = `-- name: AddTrackerCompletion :exec
INSERT INTO tracker_completions (tracker_id, completed_on)
VALUES ($1, $2)
`

type AddTrackerCompletionParams struct {
	TrackerID   uuid.UUID
	CompletedOn time.Time
}

func (q *Queries) AddTrackerCompletion(ctx context.Context, arg AddTrackerCompletionParams) error {
	_, err := q.db.Exec(ctx, addTrackerCompletion, arg.TrackerID, arg.CompletedOn)
	return err
}

const deleteTrackerCompletion = `-- name: DeleteTrackerCompletion :exec
DELETE FROM tracker_completions
WHERE tracker_id = $1
  AND completed_on = $2
`

type DeleteTrackerCompletionParams struct {
	TrackerID   uuid.UUID
	CompletedOn time.Time
}

func (q *Queries) DeleteTrackerCompletion(ctx context.Context, arg DeleteTrackerCompletionParams) error {
	_, err := q.db.Exec(ctx, deleteTrackerCompletion, arg.TrackerID, arg.CompletedOn)
	return err
}
